In [1]:
import pandas as pd

In [2]:
PROC = "C:\\ex\\data\\15_01_사출성형_공정 copy.csv"

In [3]:
LOG  = "C:\\ex\\data\\15_사출성형_로그.csv"

In [15]:
df = pd.read_csv(PROC)

In [5]:
df.columns

Index(['측정시각', '불량여부', '사이클시간', '성형사이클', '배럴온도1', '배럴온도2', '배럴온도3', '배럴온도4',
       '호퍼온도', '최대사출속도', '사출압력', '스크루위치', '전환위치', '계량시간', '계량시작점', '최대사출압',
       '전환압력', '계량시작위치', '스크루속도', '최소쿠션', '계량종료점', '감압시간'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 22 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   측정시각    250 non-null    str
 1   불량여부    250 non-null    int64
 2   사이클시간   250 non-null    float64
 3   성형사이클   250 non-null    float64
 4   배럴온도1   250 non-null    float64
 5   배럴온도2   250 non-null    float64
 6   배럴온도3   250 non-null    float64
 7   배럴온도4   250 non-null    float64
 8   호퍼온도    250 non-null    float64
 9   최대사출속도  250 non-null    float64
 10  사출압력    249 non-null    float64
 11  스크루위치   247 non-null    float64
 12  전환위치    245 non-null    float64
 13  계량시간    241 non-null    float64
 14  계량시작점   241 non-null    float64
 15  최대사출압   216 non-null    float64
 16  전환압력    216 non-null    float64
 17  계량시작위치  216 non-null    float64
 18  스크루속도   190 non-null    float64
 19  최소쿠션    182 non-null    float64
 20  계량종료점   141 non-null    float64
 21  감압시간    141 non-null    float64
dtypes: float64(20), int64(1), str(1)
memory usage: 47.7 KB

In [7]:
df.shape

(250, 22)

In [9]:
# ── [개념] 결측 제거 dropna ─────────────────────────────────────────────────
# 형식: df.dropna()(결측 행) / dropna(axis=1)(결측 열) / drop(columns=[...])
# 왜: 가장 간단하나 데이터 손실이 큼. 남는 양을 shape로 반드시 확인.

In [11]:
df.shape

(250, 22)

In [17]:
# df.dropna(inplace=True)

In [16]:
df.shape

(250, 22)

In [18]:
df.dropna(axis=1).shape

(250, 10)

In [19]:
df.shape

(250, 22)

In [20]:
# ── [개념] dropna 옵션 how·thresh·subset ────────────────────────────────────
# how='all'(완전히 빈 행만) / thresh=N(값 N개 이상 행만 유지) / subset=[열](그 열 기준)

In [21]:
print(df.dropna(how="all").shape)  # (250, 22) 거의 유지

(250, 22)

In [22]:
print(df.dropna(thresh=20).shape)  # (162, 22)

(162, 22)

In [23]:
df.dropna(thresh=20)

,측정시각,불량여부,사이클시간,성형사이클,배럴온도1,배럴온도2,배럴온도3,배럴온도4,호퍼온도,최대사출속도,...,전환위치,계량시간,계량시작점,최대사출압,전환압력,계량시작위치,스크루속도,최소쿠션,계량종료점,감압시간
1,2024-05-07 08:00:17,1,16.56,16.54,210.2,200.8,193.5,187.2,40.2,78.37,...,8.14,4.81,10.49,1211.65,1062.00,10.51,NaN,NaN,63.11,0.32
2,2024-05-07 08:00:34,1,16.58,16.56,210.1,200.7,193.5,187.2,40.2,78.32,...,8.12,4.80,10.53,1209.16,1101.41,10.54,35.38,6.02,63.11,0.32
3,2024-05-07 08:00:51,1,16.62,16.58,210.1,200.6,193.5,187.2,40.2,78.19,...,8.12,4.84,10.78,1228.24,1092.55,10.79,36.35,6.28,63.11,0.33
5,2024-05-07 08:01:25,1,16.62,16.64,210.0,200.4,193.4,187.3,40.1,78.07,...,8.11,4.87,10.92,1261.17,1176.73,10.94,NaN,6.43,63.11,0.33
7,2024-05-07 08:01:59,1,16.62,16.62,210.1,200.3,193.4,187.5,40.0,78.17,...,8.12,4.87,10.87,1285.61,1151.92,10.89,NaN,6.38,63.11,0.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,2024-05-07 09:07:09,0,16.64,16.67,209.9,200.1,195.2,190.2,40.0,78.09,...,8.12,4.77,11.08,1243.58,1227.74,11.09,NaN,6.61,63.12,0.32
239,2024-05-07 09:07:43,0,16.66,16.66,210.0,200.1,195.1,190.2,40.0,78.29,...,8.14,4.73,10.96,1265.65,1186.59,10.98,48.62,6.51,63.11,0.32
240,2024-05-07 09:08:00,0,16.68,16.69,210.0,200.0,195.0,190.2,40.0,78.20,...,8.09,4.79,10.97,1261.17,1181.97,10.99,49.12,6.51,63.11,0.32
243,2024-05-07 09:08:51,0,16.66,16.70,210.0,199.9,194.8,190.0,40.2,78.22,...,8.13,4.80,10.99,1271.64,1166.01,11.01,48.33,6.53,NaN,NaN
244,2024-05-07 09:09:08,0,16.66,16.66,210.0,200.1,194.8,190.0,40.3,78.21,...,8.11,4.79,11.04,1288.23,1162.02,11.05,45.53,6.55,NaN,NaN

In [ ]:
# ── [개념] 결측 대체 fillna(상수·평균·중앙값) ───────────────────────────────
# 형식: s.fillna(값) / s.fillna(s.mean()) / s.fillna(s.median())
# 왜: 행을 살리며 채움. 평균은 대칭 분포, 중앙값은 이상치에 강함.

In [25]:
df["스크루속도"].isna().sum()

np.int64(60)

In [27]:
pd.set_option('display.precision',1)

In [30]:
import numpy as np

In [31]:
np.set_printoptions(precision=1)

In [33]:
print(df["스크루속도"].mean())

46.89463157894737

In [29]:
round(df["스크루속도"].mean(),1)

np.float64(46.9)

In [34]:
round(df["스크루속도"].median(),1)

np.float64(47.4)

In [35]:
df["스크루속도"].isna().sum()

np.int64(60)

In [39]:
# (개념 시연 — df 원본은 그대로 두고 결과만 확인)
_demo = df["스크루속도"].fillna(df["스크루속도"].median())

In [41]:
_demo.isna().sum()

np.int64(0)

In [42]:
# ── [개념] 최빈값·ffill·bfill·groupby 대체 ─────────────────────────────────
# 범주형=mode()[0], 시계열=ffill()(앞 값)·bfill()(뒤 값), 그룹별=groupby+transform.
# ── [개념] 검증·저장 ────────────────────────────────────────────────────────
# 처리 후 isna().sum().sum()==0 확인, to_csv로 저장. inplace보다 재할당 권장.

In [43]:
pd.NaT

NaT

In [44]:
#

In [45]:
# ── [실습 1] dropna로 행·열 삭제 (사출성형 공정) ────────────────────────────

In [51]:
print(df.shape)  # (250, 22)
print(df.dropna().shape)  # (76, 22) 행 삭제
print(df.dropna(axis=1).shape)  # (250, 10) 열 삭제

(250, 22)
(76, 22)
(250, 10)

In [46]:
# ── [실습 2] dropna 옵션 조절 (사출성형 공정) ───────────────────────────────

In [52]:
print(df.dropna(how="all").shape)  # (250, 22) 거의 유지
print(df.dropna(thresh=20).shape)  # (162, 22)
print(df.dropna(subset=["불량여부"]).shape)  # 불량여부 빈 행만

(250, 22)
(162, 22)
(250, 22)

In [47]:
# ── [실습 3] 결측 비율 기준 컬럼 제거 (사출성형 공정) ───────────────────────
#  결측치 비율 0.4 이상인 칼럼(['최대사출속도', '감압시간'])은 제거

In [53]:
비율 = df.isna().sum() / len(df)
제거 = 비율[비율 > 0.4].index.tolist()  # ['최대사출속도', '감압시간']
print(제거)
print(df.drop(columns=제거).shape)  # (250, 20)

['계량종료점', '감압시간']
(250, 20)

In [48]:
# ── [실습 4] 삭제 손실 비교 (사출성형 공정) ─────────────────────────────────

In [55]:
비교 = pd.DataFrame(
    {
        "방식": ["원본", "행삭제", "thresh20"],
        "행": [len(df), len(df.dropna()), len(df.dropna(thresh=20))],
    }
)
비교["손실률"] = ((1 - 비교["행"] / len(df)) * 100).round(1)
비교  # 76(69.6%), 162(35.2%)

         방식    행   손실률
0        원본  250   0.0
1       행삭제   76  69.6
2  thresh20  162  35.2

In [49]:
# ── [실습 5] fillna 평균·중앙값 대체 (사출성형 공정) ────────────────────────

In [56]:
print(
    round(df["최대사출압"].mean(), 2), round(df["최대사출압"].median(), 2)
)  # 1241.67 1238.4
평균채움 = df["최대사출압"].fillna(df["최대사출압"].mean())
중앙채움 = df["최대사출압"].fillna(df["최대사출압"].median())
print(평균채움.isna().sum(), 중앙채움.isna().sum())  # 0 0

1262.54 1260.92
0 0

In [50]:
# 실습5까지 2시 50분까지